### ISSUE TITLE
Vague function names

### ISSUE THREAD

**Issue by readytopark** [ARTSTOCK/asx-token-dev#2]
balanceOfAt
totalSupplyAt
getValueAt

The name of the functions above should be changed to something different because they are not returning the value at specific block number anymore. Unlike MiniMe's implementation where a contract keeps track of all history of balance update, ASX token would return the latest balance in a snapshot section where a requested block number falls between.

**Comment by bezalel** [comment]
good point! to be more clear, changed function names to include "checkpoint" 
* balanceOfAt => balanceOfAtCheckpoint, totalSupplyAt => totalSupplyAtCheckpoint, getValueAt => getValueAtCheckpoint
* totalSupplyAtSnapshot function added
* documentation updated

the reason why I separated ***AtCheckpoint functions and ***AtSnapshot functions is to reduce gas consumption(not executing binary search for snapshot number validation) in the context where the queried block number is guaranteed to be a snapshot block number or recent block number after last snapshot.
